/**
 * Build HTML body structure for PDF/HTML export template
 */
export function buildExportHTML(
  logoUrl: string,
  title: string,
  subtitle: string | undefined,
  content: string,
  generatedDate: string,
  totalItems: number | undefined,
  customMeta: string | undefined,
  forPDF: boolean,
): string {
  return `  <!-- Background Elements -->
  <div class="background-grid"></div>
  <div class="corner-glow-cyan"></div>
  <div class="corner-glow-magenta"></div>
  <div class="concentric-circles">
    <div class="circle circle-1"></div>
    <div class="circle circle-2"></div>
    <div class="circle circle-3"></div>
    <div class="circle circle-4"></div>
  </div>

  <!-- Content -->
  <div class="content-wrapper">
    <!-- Header -->
    <header class="header">
      <img src="${logoUrl}" alt="PrepFlow Logo" class="logo" />
      <div class="header-content">
        <h1>PrepFlow</h1>
        <h2>${subtitle || title}</h2>
      </div>
      <div class="header-meta">
        <div>Generated: ${generatedDate}</div>
        ${totalItems !== undefined ? `<div style="margin-top: 4px;">Total Items: ${totalItems}</div>` : ''}
        ${customMeta ? `<div style="margin-top: 4px;">${customMeta}</div>` : ''}
      </div>
    </header>

    <!-- Content -->
    <div class="export-content">
      ${content}
    </div>

    <!-- Footer -->
    <footer class="footer">
      <p>Generated by PrepFlow - Kitchen Management Platform</p>
      <p style="margin-top: 4px;">www.prepflow.org</p>
    </footer>
  </div>

  ${forPDF ? '<script>window.onload = function() { window.print(); }</script>' : ''}`;
}
