// @ts-check
import tseslint from 'typescript-eslint';

/**
 * RSI Managed Configuration
 * This file is automatically generated and updated by the Recursive Self-Improvement system.
 * DO NOT EDIT MANUALLY - Changes will be overwritten.
 */

export default tseslint.config(
  {
    ignores: ['**/.next/**', '**/node_modules/**'],
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    extends: [
      ...tseslint.configs.recommended,
    ],
    rules: {
      '@typescript-eslint/no-explicit-any': 'error', // No Explicit Any (Native)
      // Validated Rules will be injected here by RSI
    },
  }
);
