// @ts-check

/**
 * RSI Managed Configuration
 * This file is automatically generated and updated by the Recursive Self-Improvement system.
 * DO NOT EDIT MANUALLY - Changes will be overwritten.
 */

/** @type {import('eslint').Linter.Config[]} */
const rsiConfig = [
  {
    // RSI Evolution Rules
    // These rules have been synthesized from historical success patterns.
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // Validated Rules will be injected here by RSI
    },
  },
];

export default rsiConfig;
