import { HfInference } from '@huggingface/inference';

export interface GeneratedRule {
  id: string;
  name: string;
  description: string;
  type: 'regex' | 'ast' | 'file-structure' | 'eslint';
  definition: string; // The regex or the ESLint rule ID
  severity: 'error' | 'warning';
  generatedFrom: string; // Insight ID
}

export class RuleGenerator {
  private static hf: HfInference | null = null;

  private static getHFClient(): HfInference | null {
    if (this.hf) return this.hf;
    const apiKey = process.env.HUGGINGFACE_API_KEY;
    if (!apiKey) return null;
    this.hf = new HfInference(apiKey);
    return this.hf;
  }

  static async generateFromInsight(insight: {
    insight: string;
    patternId: string;
  }): Promise<GeneratedRule | null> {
    // 1. Hardcoded / Native Logic (Fast Path)
    if (insight.insight.includes('Replacing "any"') || insight.patternId === 'fix-any-type') {
      return {
        id: `rule-no-any-${Date.now()}`,
        name: 'No Explicit Any (Native)',
        description: 'Native ESLint enforcement to ban "any" type.',
        type: 'eslint',
        definition: '@typescript-eslint/no-explicit-any',
        severity: 'error',
        generatedFrom: insight.patternId,
      };
    }

    // 2. LLM-Powered Dynamic Logic (Slow Path)
    // If we have an insight we don't recognize, ask the AI Brain.
    return await this.generateDynamicRuleFromLLM(insight);
  }

  private static async generateDynamicRuleFromLLM(insight: {
    insight: string;
    patternId: string;
  }): Promise<GeneratedRule | null> {
    const hf = this.getHFClient();
    if (!hf) {
      console.warn('Hugging Face API Key not found. Skipping dynamic rule generation.');
      return null;
    }
const prompt = `
      You are an expert DevOps engineer.
      Analyze this code improvement insight and map it to a standard ESLint rule.

      Insight: "${insight.insight}"
      Pattern ID: "${insight.patternId}"

      Return ONLY a JSON object with this format (no markdown, no explanation):
      {
        "name": "Human readable rule name",
        "description": "Short description",
        "eslintRuleId": "standard-eslint-rule-id-only",
        "severity": "error"
      }

      Example:
      Insight: "Removing console.log calls has 100% success."
      {"name": "No Console Logging", "description": "Prevent shipping console logs.", "eslintRuleId": "no-console", "severity": "warning"}
    `;

    try {
      const response = await hf.textGeneration({
        model: 'mistralai/Mistral-7B-Instruct-v0.2',
        inputs: `<s>[INST] ${prompt} [/INST]`,
        parameters: {
          max_new_tokens: 150,
          temperature: 0.1, // Deterministic
        },
      });

      const text = response.generated_text;
      // Extract JSON part if model chats too much (simple regex for {} block)
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (!jsonMatch) return null;

      const result = JSON.parse(jsonMatch[0]);

      if (result.eslintRuleId) {
return {
          id: `rule-llm-${Date.now()}`,
          name: result.name || 'AI Generated Rule',
          description: result.description || 'Generated by RSI LLM',
          type: 'eslint',
          definition: result.eslintRuleId,
          severity: result.severity === 'error' ? 'error' : 'warning',
          generatedFrom: insight.patternId,
        };
      }
    } catch (error) {
      console.error('LLM Generation Failed:', error);
    }
    return null;
  }
}
