/**
 * Ingredient aliases map - maps specific names to base ingredient for matching.
 * Extracted from ingredient-normalization.ts to stay under 150-line util limit.
 */
export const INGREDIENT_ALIASES: Record<string, string[]> = {
  salt: [
    'kosher salt',
    'sea salt',
    'kosher sea salt',
    'table salt',
    'fine salt',
    'coarse salt',
    'fleur de sel',
    'himalayan salt',
    'pink salt',
    'rock salt',
  ],
  pepper: [
    'black pepper',
    'white pepper',
    'ground pepper',
    'cracked pepper',
    'peppercorns',
    'freshly ground pepper',
  ],
  oil: ['vegetable oil', 'canola oil', 'sunflower oil', 'neutral oil', 'cooking oil'],
  'olive oil': ['extra virgin olive oil', 'evoo', 'light olive oil', 'pure olive oil'],
  butter: [
    'unsalted butter',
    'salted butter',
    'clarified butter',
    'melted butter',
    'softened butter',
  ],
  onion: ['brown onion', 'yellow onion', 'white onion', 'spanish onion'],
  garlic: ['garlic clove', 'garlic cloves', 'minced garlic', 'fresh garlic', 'crushed garlic'],
  sugar: ['white sugar', 'granulated sugar', 'caster sugar', 'superfine sugar'],
  'brown sugar': ['light brown sugar', 'dark brown sugar', 'muscovado'],
  flour: ['plain flour', 'all-purpose flour', 'all purpose flour', 'ap flour', 'wheat flour'],
  eggs: ['egg', 'large eggs', 'medium eggs', 'free range eggs', 'chicken eggs'],
  milk: ['whole milk', 'full cream milk', 'full fat milk', '2% milk', 'skim milk'],
  cream: ['heavy cream', 'thickened cream', 'whipping cream', 'double cream', 'single cream'],
  chicken: ['chicken breast', 'chicken thigh', 'chicken drumstick', 'chicken leg', 'chicken wing'],
  'chicken breast': ['skinless chicken breast', 'boneless chicken breast', 'chicken fillet'],
  beef: ['beef mince', 'ground beef', 'beef steak', 'stewing beef'],
  'beef mince': ['ground beef', 'minced beef', 'hamburger meat'],
  parsley: ['flat leaf parsley', 'curly parsley', 'italian parsley', 'fresh parsley'],
  basil: ['fresh basil', 'sweet basil', 'thai basil'],
  cilantro: ['coriander', 'fresh coriander', 'coriander leaves'],
  thyme: ['fresh thyme', 'thyme leaves'],
  rosemary: ['fresh rosemary', 'rosemary sprig'],
  tomato: ['roma tomato', 'cherry tomato', 'grape tomato', 'plum tomato', 'vine tomato'],
  'canned tomatoes': ['diced tomatoes', 'crushed tomatoes', 'tomato puree', 'tinned tomatoes'],
  cheese: ['cheddar', 'cheddar cheese', 'mozzarella', 'parmesan'],
  parmesan: ['parmigiano reggiano', 'grated parmesan', 'parmesan cheese'],
  vinegar: ['white vinegar', 'distilled vinegar'],
  stock: ['broth', 'chicken stock', 'beef stock', 'vegetable stock', 'chicken broth', 'beef broth'],
  'chicken stock': ['chicken broth', 'chicken bouillon'],
  rice: [
    'basmati rice',
    'jasmine rice',
    'brown rice',
    'sushi rice',
    'white rice',
    'long grain rice',
    'short grain rice',
  ],
  pasta: [
    'spaghetti',
    'penne',
    'fusilli',
    'rigatoni',
    'linguine',
    'macaroni',
    'fettuccine',
    'dried pasta',
    'fresh pasta',
  ],
  potato: [
    'baby potato',
    'new potato',
    'king edward potato',
    'maris piper',
    'russet potato',
    'sweet potato',
    'yam',
  ],
  ginger: ['fresh ginger', 'ginger root', 'grated ginger', 'minced ginger'],
  lemon: ['lemon juice', 'lemon zest', 'fresh lemon juice'],
  lime: ['lime juice', 'lime zest', 'fresh lime juice'],
  yoghurt: [
    'greek yoghurt',
    'natural yoghurt',
    'plain yoghurt',
    'low fat yoghurt',
    'full fat yoghurt',
  ],
};
