/**
 * Other category keywords (Dairy, Oils & Fats, Condiments & Sauces, Beverages, Frozen, Consumables).
 */
export const OTHER_KEYWORDS: Record<string, string[]> = {
  Dairy: [
    'milk',
    'cheese',
    'butter',
    'cream',
    'yogurt',
    'yoghurt',
    'sour cream',
    'mozzarella',
    'cheddar',
    'parmesan',
    'feta',
    'ricotta',
    'cottage cheese',
    'buttermilk',
    'ghee',
  ],
  'Oils & Fats': [
    'oil',
    'olive oil',
    'vegetable oil',
    'canola oil',
    'sunflower oil',
    'coconut oil',
    'sesame oil',
    'avocado oil',
    'butter',
    'margarine',
    'lard',
    'shortening',
  ],
  'Condiments & Sauces': [
    'ketchup',
    'tomato sauce',
    'mustard',
    'mayonnaise',
    'mayo',
    'relish',
    'pickle',
    'vinegar',
    'soy sauce',
    'worcestershire',
    'hot sauce',
    'sriracha',
    'bbq sauce',
    'barbecue sauce',
    'hollandaise',
    'pesto',
    'salsa',
    'dressing',
    'marinade',
  ],
  Beverages: [
    'juice',
    'soda',
    'soft drink',
    'coffee',
    'tea',
    'water',
    'wine',
    'beer',
    'spirits',
    'lemonade',
    'iced tea',
  ],
  Frozen: ['frozen', 'ice', 'ice cream', 'gelato', 'sorbet'],
  Consumables: [
    'napkin',
    'toothpick',
    'straw',
    'cup',
    'plate',
    'container',
    'wrap',
    'foil',
    'plastic',
    'bag',
    'paper',
  ],
};


