/**
 * Pantry category keywords (Grains, Legumes, Nuts & Seeds, Herbs & Spices).
 */
export const PANTRY_KEYWORDS: Record<string, string[]> = {
  Grains: [
    'rice',
    'pasta',
    'noodle',
    'quinoa',
    'couscous',
    'barley',
    'wheat',
    'flour',
    'bread',
    'bun',
    'roll',
    'bagel',
    'cereal',
    'oats',
    'oatmeal',
    'bulgur',
    'farro',
    'millet',
  ],
  Legumes: [
    'lentil',
    'chickpea',
    'black bean',
    'kidney bean',
    'pinto bean',
    'navy bean',
    'cannellini',
    'lima bean',
    'soybean',
    'tofu',
    'tempeh',
    'edamame',
  ],
  'Nuts & Seeds': [
    'almond',
    'walnut',
    'pecan',
    'cashew',
    'pistachio',
    'hazelnut',
    'macadamia',
    'peanut',
    'pine nut',
    'sesame',
    'sunflower seed',
    'pumpkin seed',
    'chia',
    'flax',
  ],
  'Herbs & Spices': [
    'basil',
    'parsley',
    'cilantro',
    'coriander',
    'oregano',
    'thyme',
    'rosemary',
    'sage',
    'mint',
    'dill',
    'chive',
    'tarragon',
    'paprika',
    'cumin',
    'turmeric',
    'cinnamon',
    'nutmeg',
    'pepper',
    'salt',
    'garlic powder',
    'onion powder',
    'chili',
    'chilli',
    'curry',
  ],
};




