/**
 * Produce category keywords (Fruits, Vegetables).
 */
export const PRODUCE_KEYWORDS: Record<string, string[]> = {
  Fruits: [
    'apple',
    'banana',
    'orange',
    'lemon',
    'lime',
    'grape',
    'strawberry',
    'blueberry',
    'raspberry',
    'blackberry',
    'mango',
    'pineapple',
    'watermelon',
    'melon',
    'peach',
    'pear',
    'plum',
    'cherry',
    'kiwi',
    'papaya',
    'passionfruit',
    'lychee',
  ],
  Vegetables: [
    'tomato',
    'lettuce',
    'onion',
    'carrot',
    'celery',
    'pepper',
    'bell pepper',
    'capsicum',
    'cucumber',
    'zucchini',
    'eggplant',
    'aubergine',
    'potato',
    'sweet potato',
    'pumpkin',
    'squash',
    'broccoli',
    'cauliflower',
    'cabbage',
    'spinach',
    'kale',
    'mushroom',
    'garlic',
    'ginger',
    'corn',
    'peas',
    'beans',
    'green beans',
    'asparagus',
    'artichoke',
  ],
};
