// Comprehensive Australian kitchen ingredients with realistic prices - Updated for actual table structure
export const sampleIngredients = [
  // MEAT & PROTEIN
  { 
    ingredient_name: "Beef Mince Premium", 
    brand: "Coles", 
    pack_size: 500, 
    unit: "GM", 
    cost_per_unit: 0.012, 
    trim_peel_waste_percentage: 2.00, 
    yield_percentage: 98.00, 
    supplier: "Coles", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.012,
    cost_per_unit_incl_trim: 0.0122,
    min_stock_level: 5.0,
    current_stock: 10.0,
    is_active: true
  },
  { 
    ingredient_name: "Chicken Breast Skinless", 
    brand: "Lilydale", 
    pack_size: 1000, 
    unit: "GM", 
    cost_per_unit: 0.008, 
    trim_peel_waste_percentage: 5.00, 
    yield_percentage: 95.00, 
    supplier: "Woolworths", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.008,
    cost_per_unit_incl_trim: 0.0084,
    min_stock_level: 8.0,
    current_stock: 15.0,
    is_active: true
  },
  { 
    ingredient_name: "Pork Belly", 
    brand: "Local Butcher", 
    pack_size: 2000, 
    unit: "GM", 
    cost_per_unit: 0.015, 
    trim_peel_waste_percentage: 8.00, 
    yield_percentage: 92.00, 
    supplier: "Local Butcher", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.015,
    cost_per_unit_incl_trim: 0.0163,
    min_stock_level: 3.0,
    current_stock: 6.0,
    is_active: true
  },
  { 
    ingredient_name: "Lamb Shoulder", 
    brand: "Local Butcher", 
    pack_size: 3000, 
    unit: "GM", 
    cost_per_unit: 0.018, 
    trim_peel_waste_percentage: 10.00, 
    yield_percentage: 90.00, 
    supplier: "Local Butcher", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.018,
    cost_per_unit_incl_trim: 0.0200,
    min_stock_level: 2.0,
    current_stock: 4.0,
    is_active: true
  },
  { 
    ingredient_name: "Salmon Fillet", 
    brand: "Tassal", 
    pack_size: 1000, 
    unit: "GM", 
    cost_per_unit: 0.025, 
    trim_peel_waste_percentage: 3.00, 
    yield_percentage: 97.00, 
    supplier: "Seafood Direct", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.025,
    cost_per_unit_incl_trim: 0.0258,
    min_stock_level: 4.0,
    current_stock: 8.0,
    is_active: true
  },
  { 
    ingredient_name: "Prawns Raw", 
    brand: "Banana Prawns", 
    pack_size: 1000, 
    unit: "GM", 
    cost_per_unit: 0.022, 
    trim_peel_waste_percentage: 15.00, 
    yield_percentage: 85.00, 
    supplier: "Seafood Direct", 
    storage_location: "FROZEN", 
    product_code: "",
    cost_per_unit_as_purchased: 0.022,
    cost_per_unit_incl_trim: 0.0259,
    min_stock_level: 3.0,
    current_stock: 6.0,
    is_active: true
  },
  { 
    ingredient_name: "Eggs Free Range", 
    brand: "Farm Fresh", 
    pack_size: 30, 
    unit: "PC", 
    cost_per_unit: 0.45, 
    trim_peel_waste_percentage: 0.00, 
    yield_percentage: 100.00, 
    supplier: "Local Farm", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.45,
    cost_per_unit_incl_trim: 0.45,
    min_stock_level: 2.0,
    current_stock: 5.0,
    is_active: true
  },
  
  // VEGETABLES
  { 
    ingredient_name: "Onions Brown", 
    brand: "Local Grower", 
    pack_size: 2000, 
    unit: "GM", 
    cost_per_unit: 0.002, 
    trim_peel_waste_percentage: 12.00, 
    yield_percentage: 88.00, 
    supplier: "Local Grower", 
    storage_location: "DRYSTORE", 
    product_code: "",
    cost_per_unit_as_purchased: 0.002,
    cost_per_unit_incl_trim: 0.0023,
    min_stock_level: 10.0,
    current_stock: 20.0,
    is_active: true
  },
  { 
    ingredient_name: "Garlic", 
    brand: "Local Grower", 
    pack_size: 500, 
    unit: "GM", 
    cost_per_unit: 0.008, 
    trim_peel_waste_percentage: 20.00, 
    yield_percentage: 80.00, 
    supplier: "Local Grower", 
    storage_location: "DRYSTORE", 
    product_code: "",
    cost_per_unit_as_purchased: 0.008,
    cost_per_unit_incl_trim: 0.0100,
    min_stock_level: 2.0,
    current_stock: 5.0,
    is_active: true
  },
  { 
    ingredient_name: "Carrots", 
    brand: "Local Grower", 
    pack_size: 2000, 
    unit: "GM", 
    cost_per_unit: 0.003, 
    trim_peel_waste_percentage: 8.00, 
    yield_percentage: 92.00, 
    supplier: "Local Grower", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.003,
    cost_per_unit_incl_trim: 0.0033,
    min_stock_level: 8.0,
    current_stock: 15.0,
    is_active: true
  },
  { 
    ingredient_name: "Celery", 
    brand: "Local Grower", 
    pack_size: 1000, 
    unit: "GM", 
    cost_per_unit: 0.004, 
    trim_peel_waste_percentage: 10.00, 
    yield_percentage: 90.00, 
    supplier: "Local Grower", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.004,
    cost_per_unit_incl_trim: 0.0044,
    min_stock_level: 5.0,
    current_stock: 10.0,
    is_active: true
  },
  { 
    ingredient_name: "Tomatoes Roma", 
    brand: "Local Grower", 
    pack_size: 2000, 
    unit: "GM", 
    cost_per_unit: 0.005, 
    trim_peel_waste_percentage: 5.00, 
    yield_percentage: 95.00, 
    supplier: "Local Grower", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.005,
    cost_per_unit_incl_trim: 0.0053,
    min_stock_level: 6.0,
    current_stock: 12.0,
    is_active: true
  },
  { 
    ingredient_name: "Potatoes Sebago", 
    brand: "Local Grower", 
    pack_size: 5000, 
    unit: "GM", 
    cost_per_unit: 0.002, 
    trim_peel_waste_percentage: 15.00, 
    yield_percentage: 85.00, 
    supplier: "Local Grower", 
    storage_location: "DRYSTORE", 
    product_code: "",
    cost_per_unit_as_purchased: 0.002,
    cost_per_unit_incl_trim: 0.0024,
    min_stock_level: 15.0,
    current_stock: 30.0,
    is_active: true
  },
  { 
    ingredient_name: "Mushrooms Button", 
    brand: "Local Grower", 
    pack_size: 500, 
    unit: "GM", 
    cost_per_unit: 0.012, 
    trim_peel_waste_percentage: 2.00, 
    yield_percentage: 98.00, 
    supplier: "Local Grower", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.012,
    cost_per_unit_incl_trim: 0.0122,
    min_stock_level: 3.0,
    current_stock: 6.0,
    is_active: true
  },
  { 
    ingredient_name: "Spinach Baby", 
    brand: "Local Grower", 
    pack_size: 200, 
    unit: "GM", 
    cost_per_unit: 0.025, 
    trim_peel_waste_percentage: 5.00, 
    yield_percentage: 95.00, 
    supplier: "Local Grower", 
    storage_location: "COLDROOM", 
    product_code: "",
    cost_per_unit_as_purchased: 0.025,
    cost_per_unit_incl_trim: 0.0263,
    min_stock_level: 2.0,
    current_stock: 4.0,
    is_active: true
  }
];
