/**
 * Escape HTML special characters
 */
export function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return String(text).replace(/[&<>"']/g, m => map[m]);
}

/**
 * Format PrepFlow footer text with voice
 */
export function getFooterHtml(): string {
  return `
    <p>Generated by PrepFlow - Kitchen Management Platform</p>
    <p style="margin-top: 4px;">www.prepflow.org</p>
  `;
}

/**
 * Format meta information for headers
 */
export function formatMetaInfo(meta: { totalItems?: number; customMeta?: string }): string {
  const parts: string[] = [];
  if (meta.totalItems !== undefined) {
    parts.push(`Total Items: ${meta.totalItems}`);
  }
  if (meta.customMeta) {
    parts.push(meta.customMeta);
  }
  return parts.length > 0 ? parts.join(' | ') : '';
}

