import fs from 'fs/promises';
import path from 'path';
import type { KnowledgeBasePattern, KnowledgeBaseRule } from './knowledge-base';

const ERROR_PATTERNS_FILE = path.join(process.cwd(), '.cursor/rules/error-patterns.mdc');

/**
 * Generate rule from pattern
 */
export function generateRule(pattern: KnowledgeBasePattern): KnowledgeBaseRule {
  return {
    id: `rule-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    name: pattern.name,
    source: 'error-patterns.mdc',
    enforcement: 'automated',
  };
}

/**
 * Update error-patterns.mdc with new pattern
 */
export async function updateErrorPatternsFile(
  pattern: KnowledgeBasePattern,
  _rule: KnowledgeBaseRule,
): Promise<void> {
  const patternsDir = path.dirname(ERROR_PATTERNS_FILE);
  await fs.mkdir(patternsDir, { recursive: true });

  // Check if file exists
  let content = '';
  try {
    content = await fs.readFile(ERROR_PATTERNS_FILE, 'utf8');
  } catch {
    // File doesn't exist, create default content
    content = `---
alwaysApply: true
---

# Error Patterns & Learned Fixes

This file is automatically generated and updated based on errors encountered and fixes documented in the knowledge base.

## Overview

This file contains error patterns learned from actual errors in the codebase, along with their fixes and prevention strategies.

## ${pattern.name}

### Pattern Description

${pattern.description}

### Detection

${pattern.detection}

### Fix

${pattern.fix}

### Prevention

${pattern.prevention}

`;
  }

  // Add new pattern before the last section (before "## Updating This File")
  const updateSection = `## ${pattern.name}

### Pattern Description

${pattern.description}

### Detection

${pattern.detection}

### Fix

${pattern.fix}

### Prevention

${pattern.prevention}

`;

  // Insert before "## Updating This File" section
  const updateMarker = '## Updating This File';
  if (content.includes(updateMarker)) {
    content = content.replace(updateMarker, updateSection + updateMarker);
  } else {
    // Append to end
    content += '\n' + updateSection;
  }

  await fs.writeFile(ERROR_PATTERNS_FILE, content, 'utf8');
}
