import { EquipmentType } from '../types';

export const equipmentTypes: EquipmentType[] = [
  // Cold Storage
  {
    value: 'fridge',
    label: 'Fridge',
    icon: '',
    defaultMin: 2,
    defaultMax: 8,
    category: 'Cold Storage',
  },
  {
    value: 'freezer',
    label: 'Freezer',
    icon: '',
    defaultMin: -18,
    defaultMax: -15,
    category: 'Cold Storage',
  },
  {
    value: 'walk_in_cooler',
    label: 'Walk-in Cooler',
    icon: '',
    defaultMin: 2,
    defaultMax: 8,
    category: 'Cold Storage',
  },
  {
    value: 'walk_in_freezer',
    label: 'Walk-in Freezer',
    icon: '',
    defaultMin: -18,
    defaultMax: -15,
    category: 'Cold Storage',
  },
  {
    value: 'reach_in_cooler',
    label: 'Bench Fridge',
    icon: '',
    defaultMin: 2,
    defaultMax: 8,
    category: 'Cold Storage',
  },
  {
    value: 'ice_machine',
    label: 'Ice Machine',
    icon: '',
    defaultMin: 0,
    defaultMax: 4,
    category: 'Cold Storage',
  },
  // Hot Holding
  {
    value: 'bain_marie',
    label: 'Bain Marie',
    icon: '',
    defaultMin: 63,
    defaultMax: 75,
    category: 'Hot Holding',
  },
  {
    value: 'hot_holding_cabinet',
    label: 'Hot Holding Cabinet',
    icon: '',
    defaultMin: 63,
    defaultMax: 75,
    category: 'Hot Holding',
  },
  {
    value: 'steam_table',
    label: 'Steam Table',
    icon: '',
    defaultMin: 63,
    defaultMax: 75,
    category: 'Hot Holding',
  },
  {
    value: 'warming_drawer',
    label: 'Warming Drawer',
    icon: '',
    defaultMin: 63,
    defaultMax: 75,
    category: 'Hot Holding',
  },
  {
    value: 'soup_kettle',
    label: 'Soup Kettle',
    icon: '',
    defaultMin: 63,
    defaultMax: 75,
    category: 'Hot Holding',
  },
  {
    value: 'rice_cooker',
    label: 'Rice Cooker',
    icon: '',
    defaultMin: 63,
    defaultMax: 75,
    category: 'Hot Holding',
  },
  // Cooking Equipment
  {
    value: 'combi_oven',
    label: 'Combi Oven',
    icon: '',
    defaultMin: 60,
    defaultMax: 80,
    category: 'Cooking Equipment',
  },
  {
    value: 'sous_vide',
    label: 'Sous Vide Bath',
    icon: '',
    defaultMin: 60,
    defaultMax: 80,
    category: 'Cooking Equipment',
  },
  {
    value: 'proofing_cabinet',
    label: 'Proofing Cabinet',
    icon: '',
    defaultMin: 30,
    defaultMax: 35,
    category: 'Cooking Equipment',
  },
  {
    value: 'chocolate_tempering',
    label: 'Chocolate Tempering',
    icon: '',
    defaultMin: 30,
    defaultMax: 32,
    category: 'Cooking Equipment',
  },
];
