/**
 * HTML structure generation for menu print template
 */

/**
 * Generate background elements HTML
 *
 * @returns {string} HTML for background elements
 */
export function generateBackgroundElements(): string {
  return `
    <!-- Background Elements -->
    <div class="background-grid"></div>
    <div class="corner-glow-cyan"></div>
    <div class="corner-glow-magenta"></div>
    <div class="concentric-circles">
      <div class="circle circle-1"></div>
      <div class="circle circle-2"></div>
      <div class="circle circle-3"></div>
      <div class="circle circle-4"></div>
    </div>
  `;
}

/**
 * Generate header HTML
 *
 * @param {Object} options - Header options
 * @param {string} options.logoUrl - Logo URL
 * @param {string} options.title - Menu title
 * @param {string} options.subtitle - Menu subtitle
 * @param {string} options.generatedDate - Generated date string
 * @param {number} options.totalItems - Total items count
 * @param {string} options.customMeta - Custom metadata
 * @returns {string} HTML for header
 */
export function generateHeaderHTML(options: {
  logoUrl: string;
  title: string;
  subtitle?: string;
  generatedDate: string;
  totalItems?: number;
  customMeta?: string;
}): string {
  const { logoUrl, title, subtitle, generatedDate, totalItems, customMeta } = options;

  return `
    <!-- Header -->
    <header class="header">
      <img src="${logoUrl}" alt="PrepFlow Logo" class="logo" onerror="this.style.display='none'" />
      <div class="header-content">
        <h1>PrepFlow</h1>
        <h2>${subtitle || title}</h2>
      </div>
      <div class="header-meta">
        <div>Generated: ${generatedDate}</div>
        ${totalItems !== undefined ? `<div style="margin-top: 4px;">Total Items: ${totalItems}</div>` : ''}
        ${customMeta ? `<div style="margin-top: 4px;">${customMeta}</div>` : ''}
      </div>
    </header>
  `;
}

/**
 * Generate footer HTML
 *
 * @returns {string} HTML for footer
 */
export function generateFooterHTML(): string {
  return `
    <!-- Footer -->
    <footer class="footer">
      <p>Generated by PrepFlow - Kitchen Management Platform</p>
      <p style="margin-top: 4px;">www.prepflow.org</p>
    </footer>
  `;
}

/**
 * Generate content wrapper HTML
 *
 * @param {Object} options - Content options
 * @param {string} options.content - Menu content HTML
 * @param {string} options.headerHTML - Header HTML
 * @param {string} options.footerHTML - Footer HTML
 * @returns {string} HTML for content wrapper
 */
export function generateContentWrapperHTML(options: {
  content: string;
  headerHTML: string;
  footerHTML: string;
}): string {
  const { content, headerHTML, footerHTML } = options;

  return `
    <!-- Content -->
    <div class="content-wrapper">
      ${headerHTML}

      <!-- Content -->
      <div class="export-content">
        ${content}
      </div>

      ${footerHTML}
    </div>
  `;
}
