/**
 * Category keyword mappings for rule-based detection.
 * More specific categories should come first to avoid false matches.
 */
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  Poultry: [
    'chicken',
    'turkey',
    'duck',
    'goose',
    'quail',
    'pheasant',
    'cornish',
    'poultry',
    'wing',
    'thigh',
    'breast',
    'drumstick',
  ],
  Fish: [
    'fish',
    'salmon',
    'tuna',
    'cod',
    'bass',
    'trout',
    'mackerel',
    'sardine',
    'anchovy',
    'herring',
    'snapper',
    'barramundi',
    'whiting',
    'flathead',
    'seafood',
    'prawn',
    'shrimp',
    'crab',
    'lobster',
    'oyster',
    'mussel',
    'scallop',
    'squid',
    'octopus',
  ],
  Meat: [
    'beef',
    'pork',
    'lamb',
    'veal',
    'mutton',
    'bacon',
    'ham',
    'sausage',
    'salami',
    'prosciutto',
    'chorizo',
    'steak',
    'mince',
    'ground',
  ],
  Dairy: [
    'milk',
    'cheese',
    'butter',
    'cream',
    'yogurt',
    'yoghurt',
    'sour cream',
    'mozzarella',
    'cheddar',
    'parmesan',
    'feta',
    'ricotta',
    'cottage cheese',
    'buttermilk',
    'ghee',
  ],
  Fruits: [
    'apple',
    'banana',
    'orange',
    'lemon',
    'lime',
    'grape',
    'strawberry',
    'blueberry',
    'raspberry',
    'blackberry',
    'mango',
    'pineapple',
    'watermelon',
    'melon',
    'peach',
    'pear',
    'plum',
    'cherry',
    'kiwi',
    'papaya',
    'passionfruit',
    'lychee',
  ],
  Vegetables: [
    'tomato',
    'lettuce',
    'onion',
    'carrot',
    'celery',
    'pepper',
    'bell pepper',
    'capsicum',
    'cucumber',
    'zucchini',
    'eggplant',
    'aubergine',
    'potato',
    'sweet potato',
    'pumpkin',
    'squash',
    'broccoli',
    'cauliflower',
    'cabbage',
    'spinach',
    'kale',
    'mushroom',
    'garlic',
    'ginger',
    'corn',
    'peas',
    'beans',
    'green beans',
    'asparagus',
    'artichoke',
  ],
  Grains: [
    'rice',
    'pasta',
    'noodle',
    'quinoa',
    'couscous',
    'barley',
    'wheat',
    'flour',
    'bread',
    'bun',
    'roll',
    'bagel',
    'cereal',
    'oats',
    'oatmeal',
    'bulgur',
    'farro',
    'millet',
  ],
  Legumes: [
    'lentil',
    'chickpea',
    'black bean',
    'kidney bean',
    'pinto bean',
    'navy bean',
    'cannellini',
    'lima bean',
    'soybean',
    'tofu',
    'tempeh',
    'edamame',
  ],
  'Nuts & Seeds': [
    'almond',
    'walnut',
    'pecan',
    'cashew',
    'pistachio',
    'hazelnut',
    'macadamia',
    'peanut',
    'pine nut',
    'sesame',
    'sunflower seed',
    'pumpkin seed',
    'chia',
    'flax',
  ],
  'Herbs & Spices': [
    'basil',
    'parsley',
    'cilantro',
    'coriander',
    'oregano',
    'thyme',
    'rosemary',
    'sage',
    'mint',
    'dill',
    'chive',
    'tarragon',
    'paprika',
    'cumin',
    'turmeric',
    'cinnamon',
    'nutmeg',
    'pepper',
    'salt',
    'garlic powder',
    'onion powder',
    'chili',
    'chilli',
    'curry',
  ],
  'Oils & Fats': [
    'oil',
    'olive oil',
    'vegetable oil',
    'canola oil',
    'sunflower oil',
    'coconut oil',
    'sesame oil',
    'avocado oil',
    'butter',
    'margarine',
    'lard',
    'shortening',
  ],
  'Condiments & Sauces': [
    'ketchup',
    'tomato sauce',
    'mustard',
    'mayonnaise',
    'mayo',
    'relish',
    'pickle',
    'vinegar',
    'soy sauce',
    'worcestershire',
    'hot sauce',
    'sriracha',
    'bbq sauce',
    'barbecue sauce',
    'hollandaise',
    'pesto',
    'salsa',
    'dressing',
    'marinade',
  ],
  Beverages: [
    'juice',
    'soda',
    'soft drink',
    'coffee',
    'tea',
    'water',
    'wine',
    'beer',
    'spirits',
    'lemonade',
    'iced tea',
  ],
  Frozen: ['frozen', 'ice', 'ice cream', 'gelato', 'sorbet'],
  Consumables: [
    'napkin',
    'toothpick',
    'straw',
    'cup',
    'plate',
    'container',
    'wrap',
    'foil',
    'plastic',
    'bag',
    'paper',
  ],
};
