/**
 * Generate PDF content for a recipe (simplified implementation).
 * In production, use a library like puppeteer or jsPDF.
 *
 * @param {Object} recipe - Recipe object with ingredients and instructions
 * @returns {string} PDF content as text
 */
export function generateRecipePDF(recipe: any): string {
  const ingredients = recipe.recipe_ingredients
    .map(
      (ri: any) =>
        `• ${ri.quantity} ${ri.unit} ${ri.ingredients.name}${ri.notes ? ` (${ri.notes})` : ''}`,
    )
    .join('\n');

  const pdfContent = `
RECIPE: ${recipe.name}
${recipe.description ? `\nDescription: ${recipe.description}` : ''}

INGREDIENTS:
${ingredients}

INSTRUCTIONS:
${recipe.instructions || 'No instructions provided'}

${recipe.notes ? `\nNOTES:\n${recipe.notes}` : ''}

---
Generated by PrepFlow
${new Date().toLocaleDateString()}
  `.trim();

  return pdfContent;
}
