/**
 * Generate QA Audit Report.
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { ErrorRecord } from '../../fixtures/global-error-listener';
import type { TestResultsSummary } from '../../helpers/report-generator';

/**
 * Generate QA Audit Report.
 */
export function generateQAReport(
  TEST_PREFIX: string,
  visitedPages: Set<string>,
  errors: ErrorRecord[],
  screenshots: string[],
): void {
  const errorTableRows =
    errors.length > 0
      ? errors.map(err => {
          const errorType =
            err.type === 'network' ? `Network ${err.statusCode || 'N/A'}` : err.type;
          const message = err.message.substring(0, 100).replace(/\|/g, '\\|').replace(/\n/g, ' ');
          return `| ${err.url.substring(0, 80)} | ${errorType} | ${message} | ${err.timestamp} |`;
        })
      : ['| No errors found | - | - | - |'];

  const detailedReport = [
    '# QA Audit Report',
    '',
    `**Generated:** ${new Date().toISOString()}`,
    `**Test Prefix:** ${TEST_PREFIX}`,
    '',
    '## Summary',
    '',
    `- **Total Pages Visited:** ${visitedPages.size}`,
    `- **Total Errors Found:** ${errors.length}`,
    '',
    '## Error Log',
    '',
    '| URL | Error Type (Console/Network) | Message | Timestamp |',
    '|-----|------------------------------|---------|-----------|',
    ...errorTableRows,
    '',
    '## Screenshots',
    '',
    ...(screenshots.length > 0
      ? screenshots.map(path => `- \`${path}\``)
      : ['- No screenshots taken']),
    '',
    '---',
    '',
    '*This report was automatically generated by the System Audit E2E test suite.*',
  ];

  writeFileSync(join(process.cwd(), 'QA_AUDIT_REPORT.md'), detailedReport.join('\n'), 'utf-8');
  console.log(`✅ QA Audit Report generated: QA_AUDIT_REPORT.md`);
  console.log(`   📊 Summary: ${visitedPages.size} pages visited, ${errors.length} errors found`);
  console.log(`   📸 Screenshots: ${screenshots.length} taken`);
}



