/**
 * Template utility functions for print/export templates
 * Provides consistent formatting, logo loading, and content escaping
 */

import { logger } from '@/lib/logger';

/**
 * Format date in Australian format (DD/MM/YYYY HH:MM)
 *
 * @param {Date} date - Date to format
 * @returns {string} Formatted date string
 */
export function formatDateAustralian(date: Date = new Date()): string {
  return date.toLocaleString('en-AU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Format date for print/export headers (shorter format)
 *
 * @param {Date} date - Date to format
 * @returns {string} Formatted date string
 */
export function formatDateShort(date: Date = new Date()): string {
  return date.toLocaleString('en-AU', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Get logo URL for client-side use (public URL)
 *
 * @returns {string} Public URL to PrepFlow logo
 */
export function getLogoUrl(): string {
  return '/images/prepflow-logo.png';
}

/**
 * Format meta information for headers
 *
 * @param {Object} meta - Meta information object
 * @param {number} [meta.totalItems] - Total number of items
 * @param {string} [meta.customMeta] - Custom metadata string
 * @returns {string} Formatted meta HTML
 */
export function formatMetaInfo(meta: { totalItems?: number; customMeta?: string }): string {
  const parts: string[] = [];
  if (meta.totalItems !== undefined) {
    parts.push(`Total Items: ${meta.totalItems}`);
  }
  if (meta.customMeta) {
    parts.push(meta.customMeta);
  }
  return parts.length > 0 ? parts.join(' | ') : '';
}

/**
 * Escape HTML special characters (enhanced version)
 *
 * @param {string} text - Text to escape
 * @returns {string} Escaped HTML string
 */
export function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return String(text).replace(/[&<>"']/g, m => map[m]);
}

/**
 * Format PrepFlow footer text with voice
 *
 * @returns {string} Footer HTML
 */
export function getFooterHtml(): string {
  return `
    <p>Generated by PrepFlow - Kitchen Management Platform</p>
    <p style="margin-top: 4px;">www.prepflow.org</p>
  `;
}

/**
 * Template variant type
 */
export type TemplateVariant =
  | 'default'
  | 'kitchen'
  | 'customer'
  | 'supplier'
  | 'compliance'
  | 'compact';

/**
 * Get recommended variant for a content type
 *
 * @param {string} contentType - Type of content ('prep-list' | 'menu' | 'order-list' | 'compliance' | 'temperature' | 'cleaning')
 * @param {Object} context - Additional context
 * @param {boolean} [context.isCustomerFacing] - Is this for customer viewing?
 * @param {boolean} [context.isKitchenUse] - Is this for kitchen staff?
 * @param {boolean} [context.isAudit] - Is this for audit/compliance?
 * @param {boolean} [context.isSupplier] - Is this for supplier?
 * @returns {TemplateVariant} Recommended variant
 *
 * @example
 * ```typescript
 * getRecommendedVariant('menu', { isCustomerFacing: true }) // 'customer'
 * getRecommendedVariant('prep-list', { isKitchenUse: true }) // 'kitchen'
 * getRecommendedVariant('order-list', { isSupplier: true }) // 'supplier'
 * ```
 */
export function getRecommendedVariant(
  contentType: string,
  context: {
    isCustomerFacing?: boolean;
    isKitchenUse?: boolean;
    isAudit?: boolean;
    isSupplier?: boolean;
  } = {},
): TemplateVariant {
  const { isCustomerFacing, isKitchenUse, isAudit, isSupplier } = context;

  // Supplier orders
  if (isSupplier || contentType === 'order-list') {
    return 'supplier';
  }

  // Compliance/audit reports
  if (
    isAudit ||
    contentType === 'compliance' ||
    contentType === 'temperature' ||
    contentType === 'cleaning'
  ) {
    return 'compliance';
  }

  // Customer-facing menus
  if (isCustomerFacing || contentType === 'menu') {
    return 'customer';
  }

  // Kitchen prep lists
  if (isKitchenUse || contentType === 'prep-list') {
    return 'kitchen';
  }

  // Default
  return 'default';
}

/**
 * Format currency in Australian Dollars
 *
 * @param {number} amount - Amount to format
 * @param {boolean} [includeSymbol=true] - Include currency symbol
 * @returns {string} Formatted currency string
 *
 * @example
 * ```typescript
 * formatCurrency(29.99) // '$29.99'
 * formatCurrency(29.99, false) // '29.99'
 * ```
 */
export function formatCurrency(amount: number, includeSymbol: boolean = true): string {
  if (includeSymbol) {
    return new Intl.NumberFormat('en-AU', {
      style: 'currency',
      currency: 'AUD',
    }).format(amount);
  }
  return new Intl.NumberFormat('en-AU', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

/**
 * Format date range for reports
 *
 * @param {string} startDate - Start date (ISO string)
 * @param {string} endDate - End date (ISO string)
 * @returns {string} Formatted date range string
 *
 * @example
 * ```typescript
 * formatDateRange('2025-01-01', '2025-01-31') // '1 January 2025 - 31 January 2025'
 * ```
 */
export function formatDateRange(startDate: string, endDate: string): string {
  const start = new Date(startDate).toLocaleDateString('en-AU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const end = new Date(endDate).toLocaleDateString('en-AU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  return `${start} - ${end}`;
}

/**
 * Get variant description for UI display
 *
 * @param {TemplateVariant} variant - Template variant
 * @returns {string} Human-readable description
 */
export function getVariantDescription(variant: TemplateVariant): string {
  const descriptions: Record<TemplateVariant, string> = {
    default: 'Standard format with full PrepFlow branding',
    kitchen: 'Compact layout with checkboxes for kitchen use',
    customer: 'Polished design for customer-facing menus',
    supplier: 'Purchase order format for supplier orders',
    compliance: 'Audit-ready formal layout for compliance reports',
    compact: 'Compact layout with minimal spacing',
  };
  return descriptions[variant] || descriptions.default;
}

/**
 * Get variant display name for UI
 *
 * @param {TemplateVariant} variant - Template variant
 * @returns {string} Display name
 */
export function getVariantDisplayName(variant: TemplateVariant): string {
  const names: Record<TemplateVariant, string> = {
    default: 'Standard',
    kitchen: 'Kitchen',
    customer: 'Customer',
    supplier: 'Supplier',
    compliance: 'Compliance',
    compact: 'Compact',
  };
  return names[variant] || 'Standard';
}
